services:
  spring-app:
    build: .
    container_name: bookstore-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ep-blue-recipe-a2xzjkqd-pooler.eu-central-1.aws.neon.tech/neondb
      SPRING_DATASOURCE_USERNAME: neondb_owner
      SPRING_DATASOURCE_PASSWORD: npg_vh7lW5IGMNJS
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      JWT_SECRET_KEY: "CJToY20Wyu0WJWkAKH30XPdMiGLoyQ7t"
    restart: unless-stopped