services:
  spring-app:
    env_file:
      .env
    build: .
    container_name: bookstore-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${spring_datasource_url}
      SPRING_DATASOURCE_USERNAME: ${spring_datasource_username}
      SPRING_DATASOURCE_PASSWORD: ${spring_datasource_password}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      JWT_SECRET_KEY: ${jwt_secret_key}
    restart: unless-stopped